### ISSUE TITLE
lost Cargo.toml

### ISSUE THREAD

**Issue by CMingTseng** [termux/termux-packaging#4] opened 2019-10-28 07:52 UTC
Dear Sir

when i clone this project 

and then 

run  make 

or 

input { " docker run  --rm -it fredrikfornwall/rust-static-builder sh"}

i get 

could not find `Cargo.toml` in `/build` or any parent directory

THX

**Comment by ghost** [comment] 2020-06-06 19:57
Closing as I can't reproduce it:
```
~/.../Termux/termux-packaging $ make
docker run --rm -v "/home/k-17/Development/Termux/termux-packaging":/build fredrikfornwall/rust-static-builder:1.43.1
Unable to find image 'fredrikfornwall/rust-static-builder:1.43.1' locally
1.43.1: Pulling from fredrikfornwall/rust-static-builder
d51af753c3d3: Already exists 
fc878cd0a91c: Already exists 
6154df8ff988: Already exists 
fee5db0ff82f: Already exists 
78007502cd7b: Pull complete 
4edac6031c9a: Pull complete 
13ce409f195e: Pull complete 
38c69b23bba8: Pull complete 
92ee4303d3e3: Pull complete 
792136344b49: Pull complete 
443cb9222fe3: Pull complete 
1152c845c9ee: Pull complete 
5b3055e6765a: Pull complete 
6e6a2a362063: Pull complete 
Digest: sha256:653ed637d8e6be86ac92fc714f028bcb9b1ca391d7477fc55119eca5a4c9ef3d
Status: Downloaded newer image for fredrikfornwall/rust-static-builder:1.43.1
    Updating crates.io index
 Downloading crates ...
  Downloaded walkdir v2.3.1
  Downloaded ar v0.8.0
  Downloaded reqwest v0.10.4
  Downloaded structopt v0.3.14
  Downloaded tar v0.4.26
  Downloaded md5 v0.7.0
... some lines are skipped ...
   Compiling structopt v0.3.14
   Compiling hyper v0.13.5
   Compiling hyper-tls v0.4.1
   Compiling reqwest v0.10.4
   Compiling termux-packaging v0.1.0 (/build)
    Finished release [optimized] target(s) in 5m 50s
```

**Closed as completed by ghost** 2020-06-06 19:57 UTC

**Comment by ghost** [comment] 2020-06-06 19:59
> input { " docker run --rm -it fredrikfornwall/rust-static-builder sh"}

This command will not work if volume with Cargo.toml and sources is not mounted.
